version: '3'
services:
  node-service:
    build: ./api
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - node-service

volumes:
  db_data: