version: '3'
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=books
    depends_on:
      - db

  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=books
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - api

volumes:
  db_data: